export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const LOAD_TASK_SUCCESS = 'LOAD_TASK_SUCCESS';
export const SAVE_TASK_SUCCESS = 'SAVE_TASK_SUCCESS';

export const LOAD_STATUSES_SUCCESS = 'LOAD_STATUSES_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';