export const CREATE_TASK = 'CREATE_TASK';
export const LOAD_TASK_SUCCESS = 'LOAD_TASK_SUCCESS';
export const SAVE_TASK_SUCCESS = 'SAVE_TASK_SUCCESS';

export const LOAD_STATUSES_SUCCESS = 'LOAD_STATUSES_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';